### ISSUE TITLE
BeerVerificationListenerTest doesn't work in 2.1.x

### ISSUE THREAD

**Issue by b-dzoba** [spring-cloud-samples/spring-cloud-contract-samples#39] opened 2018-12-27 11:42 UTC
Seems like this test depends on ordering in HashMap. For me it works with destination=verifications, but fails with destination=aa.
```
2018-12-27 13:26:40.708 DEBUG 150088 --- [           main] o.s.c.c.v.m.stream.StreamStubMessages    : Found following channels [{aa=aa, input=aa}] for destination [aa]. Will pick the one that matches the default channel name or the first one if none is matching
2018-12-27 13:26:40.708 DEBUG 150088 --- [           main] o.s.c.c.v.m.stream.StreamStubMessages    : Picked channel name is [aa]
```
https://github.com/b-dzoba/spring-cloud-contract-samples/commit/82bc41febe5d4d8dde306d8d0798aebeecb49a7c

**Comment by marcingrzejszczak** [comment] 2019-02-19 21:23
@b-dzoba is it still a problem? I haven't noticed this issue :|

**Comment by b-dzoba** [comment] 2019-03-04 14:37
@marcingrzejszczak BeerVerificationListenerTest calls `resolvedDestination` method which takes the first element from [HashMap](https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/messaging/stream/StreamStubMessages.java#L124). Sometimes it picks the wrong channel and fails (when "input" is the second element in the map).
![channels](https://user-images.githubusercontent.com/30266053/53739818-65c87600-3e9b-11e9-8bfe-376da015f8e0.PNG)

**Comment by kriskrishna** [comment] 2019-03-25 01:09
Yes, I am facing this exact issue too. Do we have a fix for this now?

**Comment by OlgaMaciaszek** [comment] 2019-04-17 10:13
Caused by: https://github.com/spring-cloud/spring-cloud-contract/issues/1044

**Comment by OlgaMaciaszek** [comment] 2019-04-25 07:52
Fixed by https://github.com/spring-cloud/spring-cloud-contract/commit/1ad2704000d26e15660c48dae2a7030404f7907e

**Closed by OlgaMaciaszek** 2019-04-25 07:52 UTC
Labels: bug, in progress
